#!usr/bin/env php
<?php
/**
 * Ejecutable. Realiza tareas de mantenimiento.
 *
 * Uso: $ console database [opción] // tareas de la base de datos
 *
 * @version 0.1 09ABR18
 * @author diego.viniegra@gmail.com
 */

include_once 'bootstrap.php';

switch ($argv[1]) {
    case 'database':
        include_once 'bin/database.php';
        break;

    default:
        # code...
        break;
}
