#!usr/bin/env php
<?php
/**
 * Ejecutable. Inicia el servidor.
 *
 * @param pendiente
 * @version 0.1 09ABR18
 * @author diego.viniegra@gmail.com
 */

use Websocket\SocketServer;

include_once 'bootstrap.php';

$srv = new SocketServer(SRV_HOST, SRV_PORT);

try {
  $srv->run();
}
catch (Exception $e) {
  $srv->stdout($e->getMessage());
}
